version: '3'

services:
  login_register:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    image: login_register
    container_name: login_register
    restart: unless-stopped
    volumes:
      - ./:/var/www
    depends_on:
      - webserver
      - db
    networks:
      - app-network
  webserver:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    image: nginx
    container_name: webserver
    restart: unless-stopped
    ports: 
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - app-network
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: mysecretpassword
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
    driver: local